name: Deploy Java application

on: 
  push:
      branches: [main]
      paths: 
        - ".github/**"
        - "backend/**"
        - "!frontend/**"

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./backend
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
                
            - name: Build project
              run: mvn clean install -DskipTests
            -
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            # - name: Login Docker Hub
            #   run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
            
            - name: Build Docker image
              run: docker build -t douglasmatosdev/goals .
            
            - name: Push image docker hub
              run: docker push douglasmatosdev/goals
    
    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Create network
          run: docker network create goals-network

        - name: Pull mysql image
          run: docker pull mysql/mysql-server:8.0.32

        - name: Remove docker mysql_container
          run: docker rm -f mysql_container
        
        - name: Run docker mysql_container
          run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD='${{secrets.GOALS_DATABASE_PASSWORD}}' --name mysql_container mysql/mysql-server:8.0.32

        - name: Pull goals image from Docker hub
          run: docker pull douglasmatosdev/goals:latest

        - name: Remove docker goals_container
          run: docker rm -f goals_container
        
        - name: Run docker goals_container
          run: docker run -d -p 8080:8080 -e GOALS_ORIGIN_PATTERNS=${{secrets.GOALS_ORIGIN_PATTERNS}} -e GOALS_JWT_TOKEN_SECRET_KEY=${{secrets.GOALS_JWT_TOKEN_SECRET_KEY}} -e GOALS_JWT_TOKEN_SECRET_EXPIRE_LENGTH=${{secrets.GOALS_JWT_TOKEN_SECRET_EXPIRE_LENGTH}} -e GOALS_DATABASE_NAME=${{secrets.GOALS_DATABASE_NAME}} -e GOALS_DATABASE_HOST=${{secrets.GOALS_DATABASE_HOST}} -e GOALS_DATABASE_PORT=${{secrets.GOALS_DATABASE_PORT}} -e GOALS_DATABASE_USERNAME=${{secrets.GOALS_DATABASE_USERNAME}} -e GOALS_DATABASE_PASSWORD='${{secrets.GOALS_DATABASE_PASSWORD}}' --name goals_container douglasmatosdev/goals